spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 9d41dada285fee32f9ca
            client-secret: 8bdab9e751e8c0171bd986f7ab55ad4db9305dd0
          google:
            client-id: 951068135767-kuuk8r1520ta9gp02aggu9ac4tl86oq7.apps.googleusercontent.com
            client-secret: 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